[package]
name = "server"
version = "0.1.0"
authors = ["Alex Kornitzer <a.kornitzer@me.com>"]
edition = "2018"

[dependencies]
nng = { version = "1.0.0-rc.2" }
uuid = { version = "0.8", features = ["v4"] }
